repos:
  - repo: local
    hooks:
      - id: gitprefix
        name: Git Prefix
        description: Prefix commit messages with issue/branch information
        entry: ./prefix.sh
        language: script
        stages: [prepare-commit-msg]
        pass_filenames: false
        args: [.git/COMMIT_EDITMSG]